CREATE TABLE EMPLOYEE(
	ID INT PRIMARY KEY NOT NULL,
	SURNAME TEXT NOT NULL,
	NAME TEXT NOT NULL,
	DATEBIRTH DATE,
	PHONENUMBER TEXT CHECK (PHONE_NUMBER ~ '^\+\d{2}\(\d{3}\)\d{3}-\d{2}-\d{2}$'),
	APPOINTMENT TEXT,
	SALARY REAL
);

CREATE TABLE MENU(
	NUM_MENU INT UNIQUE PRIMARY KEY NOT NULL,
	MENU_NAME TEXT NOT NULL
);

CREATE TABLE INGREDIENT(
	NUM_INGREDIENT INT PRIMARY KEY NOT NULL,
	INGREDIENT_NAME TEXT NOT NULL
);

CREATE TABLE WAREHOUSE(
	INGREDIENT_ID INT UNIQUE REFERENCES INGREDIENT (ID),
	AMOUNT REAL,
	UNIT TEXT
);

CREATE TABLE DISH(
	NUM_DISH INT UNIQUE PRIMARY KEY NOT NULL,
	DISH_NAME TEXT NOT NULL,
	COST REAL,
	WEIGHT REAL,
	CATEGORY_ID INT REFERENCES MENU (ID)
);

CREATE TABLE DISH_INGREDIENT(
	DISH_ID INT REFERENCES DISH (ID),
	INGREDIENT_ID INT REFERENCES INGREDIENT (ID)
);

CREATE TABLE MENU_DISHES(
	MENU_ID INT REFERENCES MENU (ID),
	DISH_ID INT REFERENCES DISH (ID)
);

CREATE TABLE GUEST_ORDER(
	ID INT PRIMARY KEY NOT NULL,
	TABLE_NUMBER INT,
	DATE_ORDER DATE,
	EMPLOYEE_ID INT REFERENCES EMPLOYEE (ID),
	ISCLOSED boolean
);

CREATE TABLE DISH_ORDER(
	ID SERIAL,
	ORDER_ID INT REFERENCES ORDERS (ID),
	DISH_ID INT REFERENCES DISH (ID),
	IS_CREATED boolean
);

CREATE TABLE DISH_CREATED(
	ID INT NOT NULL,
	DISH_NUMBER INT REFERENCES DISH (ID),
	EMPLOYEE_ID INT REFERENCES EMPLOYEE (ID),
	ORDER_ID INT REFERENCES GUEST_ORDER (ID)
);